#include <zephyr/kernel.h>
#include <zephyr/init.h>
#include <zephyr/sys/printk.h>

#include <zmk/event_manager.h>
#include <zmk/events/position_state_changed.h>
#include <zmk/pm.h>

#if defined(CONFIG_ZMK_PM_SOFT_OFF)

/* ============================================================
 * MUSTAFA KEYBOARD - AUTO OFF
 *
 * 0      = OFF
 * 2000   = 2 seconds
 * 10000  = 10 seconds
 * 15000  = 15 seconds
 * 20000  = 20 seconds
 * ============================================================ */

static uint32_t auto_off_timeout_ms = 0;
static struct k_work_delayable auto_off_work;

static void auto_off_work_handler(struct k_work *work)
{
    ARG_UNUSED(work);

    if (auto_off_timeout_ms == 0) {
        return;
    }

    printk("Mustafa Auto-Off: Soft Off\n");

    /* Use the same ZMK soft-off path as &soft_off. */
    zmk_pm_soft_off();
}

static void auto_off_reset_timer(void)
{
    if (auto_off_timeout_ms == 0) {
        k_work_cancel_delayable(&auto_off_work);
        return;
    }

    k_work_reschedule(
        &auto_off_work,
        K_MSEC(auto_off_timeout_ms)
    );
}

/*
 * Position-state events are generated by the matrix for every
 * key press/release. This is intentionally used instead of the
 * higher-level activity-state event so every key event resets
 * the Auto-Off timer.
 */
static int auto_off_position_listener(const zmk_event_t *eh)
{
    struct zmk_position_state_changed *event;

    event = as_zmk_position_state_changed(eh);

    if (event == NULL) {
        return 0;
    }

    auto_off_reset_timer();

    return 0;
}

ZMK_LISTENER(
    auto_off_position_listener,
    auto_off_position_listener
);

ZMK_SUBSCRIPTION(
    auto_off_position_listener,
    zmk_position_state_changed
);

/* Called by control_service.c. */
void mustafa_auto_off_set(uint32_t timeout_ms)
{
    auto_off_timeout_ms = timeout_ms;

    k_work_cancel_delayable(&auto_off_work);

    if (auto_off_timeout_ms == 0) {
        printk("Mustafa Auto-Off: OFF\n");
        return;
    }

    printk(
        "Mustafa Auto-Off: %u ms\n",
        auto_off_timeout_ms
    );

    auto_off_reset_timer();
}

static int mustafa_auto_off_init(void)
{
    k_work_init_delayable(
        &auto_off_work,
        auto_off_work_handler
    );

    printk("Mustafa Auto-Off initialized\n");

    return 0;
}

SYS_INIT(
    mustafa_auto_off_init,
    APPLICATION,
    95
);

#endif /* CONFIG_ZMK_PM_SOFT_OFF */
